server:
  port: ${PORT:8080}
spring:
  application:
    name: jmdt-stock-manager
  datasource:
    url: jdbc:postgresql://localhost:5432/stockManagerV2
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
